############################
## CHANGE THESE
############################

baseURL: 'https://dom-wuest.de'
title: Dominik Wüst

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']

defaultContentLanguage: en

languages:
  de:
    contentDir: content
    disabled: false
    languageCode: de-DE
    languageDirection: ltr
    languageName: Deutsch
    params:
      bio: Biografie
      publishedwith: Erstellt mit
    weight: 1
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      bio: Biography
      publishedwith: Published with
    weight: 2