############################
## CHANGE THESE
############################

baseURL: 'https://dom-wuest.github.io/Portfolio'
title: Portfolio

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


