############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Projects & Research
  url: /blog/
  weight: 20
- name: About Me
  url: /about/
  weight: 30