############################
## Navbar
############################

main:
- name: Startseite
  url: /de/
  weight: 10
- name: Forschung
  url: /de/research/
  weight: 20
- name: Entwicklung
  url: /de/development/
  weight: 30
- name: Blog
  url: /de/blog/
  weight: 40
- name: Über Mich
  url: /de/about/
  weight: 50