############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Research
  url: /research/
  weight: 20
- name: Development
  url: /development/
  weight: 30
- name: Blog
  url: /blog/
  weight: 40
- name: About Me
  url: /about/
  weight: 50