############################
## Navbar
############################

main:
- name: Startseite
  url: /de/
  weight: 10
- name: Projekte & Forschung
  url: /de/blog/
  weight: 20
- name: Über Mich
  url: /de/about/
  weight: 30