############################
## Author
############################

author:
  name: Dominik Wüst
  image: author.png
  greeting: "»It always seems impossible until it's done.« (Nelson Mandela)"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/dom-wuest
  # - link: https://github.com/dom-wuest/Portfolio#readme
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/dom-wuest
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:kontakt@dom-wuest.de
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: Dominik Wüst
description: "Learn more about my projects and research."
images:
  - logo.png
